### ISSUE TITLE
Форматирование стилей

### ISSUE THREAD

**Issue by Frolikow** [arkhannanov/FSD_CV#10]
В стилях не стесняйся между блоками правил добавлять отступ. Гораздо легче читаться будет.
вместо
```scss
.contact {
  width: 100%;
  .contact-wrapper {
    width: 100%;
    margin-bottom: 80px;
    .contact-wrapper__item {
      margin-top:20px;
      margin-bottom: 20px;
    }
  }
}
```
лучше сделать
```scss
.contact {
  width: 100%;

  .contact-wrapper {
    width: 100%;
    margin-bottom: 80px;

    .contact-wrapper__item {
      margin-top:20px;
      margin-bottom: 20px;
    }
  }
}
```
