### ISSUE TITLE
блок page

### ISSUE THREAD

**Issue by Frolikow** [arkhannanov/FSD_CV#17]
почему эти стили находятся в стилях блок `page`?
```scss
h1, h2, h3, h4, h5, h6 { 
    margin: 0; 
    font-family: $boldFont;
  }
  
a {
    text-decoration: none;
}
  
main {
  width: 100%;
  height: 100%;
  padding: 0;
  margin: 0;
}
```
